apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: voting-app
  ports:
    - port: 80
      nodePort: 30000  
      targetPort: 80

      #if you dont specify type it will create clusterIP type service
