apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379  #port of the clusterIP service
      targetPort: 6379  #port of the pod container port

      #if you dont specify type it will create clusterIP type service
      
