apiVersion: v1
kind: Service
metadata:
  name: my-service-resultapp
spec:
  type: NodePort
  selector:
    app: result-app
  ports:
    - port: 80 #port of the clusterIP service
      targetPort: 80  #port of the pod container port
      nodePort: 30001
      #if you dont specify type it will create clusterIP type service
      
